SPILL_STRING = (
"Spil temen yg mesum akut",
"Spil yang anti pacaran",
"Spil tempat favorite pas lagi galau",
"Spil yg paling cengeng",
"Spil top3 lagu yang sering lu dengerin",
"Spil bar notif lu sekarang",
"Spil orang yg bikin lu ngakak",
"Spil dm ig",
"Spil ukuran celana/rok",
"Spil temen kamu yang gatau diri",
"Spil temen yang pelit jawaban",
"Spil orang yang paling polos?",
"Spil orang yang paling dibenci",
"kirim stiker paling berdosa lu",
"Spil orang yg bikin lu mood lagi",
"Spil yang kebanyakan halu",
"Spil hal terbodoh yang pernah lu lakuin",
"Spil kalian kalo mandi apa yang pertama kalian lakukan",
"Spil stiker favorit mu",
"Spil bestie lwan jnis lu yng bkin lu tkut kehilangan",
"Spil orang yg pengen di jedor",
"Spil orang yg selalu bikin kamu sakit hati tapi kamu masih tetep sayang",
"Pernah nyakitin cp kamu? Ceritain",
"Kamu gak suka cp kamu pas dia ngapain?",
"Spil aktris indonesia fav lu",
"Spil orang yg buat lu down se down down nya",
"Spil cinta pertama",
"Spil siapa yang paling enak jadi tempat curhat?",
"kenapa cowo mandang fisik?",
"Spil orang paling kamu sayang",
"Spil temen terdekat lu di gc ini",
"Spil snack favorit mu",
"Spil lebih suka yg panjang tp kecil atau pendek tp gede",
"Spil orang yg lu suka di gc",
"Spil chat terbaper",
"Spil yg merubah sikap Lo menjadi skrng",
"Spil lagu yang wajib banget didengerin",
"Spil mimpi kalian yang teraneh",
"Spil minuman teraneh yang pernah kamu minum",
"Spil yang sering php, tag orangnya!",
"Spil mimpi teraneh",
"Spil uname twitter lu",
"berapa kali lo ganti warna rambut? warna apa aja?",
"Spil ukuran sempak",
"Spil meninggalkan atau menanti",
"Spil tinggi badan kamu",
"Spil psikopat terhebat",
"Spil theme telegram",
"Spil waktu bucin pernah bikin apa ke mantan buat kenang2an",
"Spil kencan idaman",
"Spil berantem sama cp biasanya karna apa",
"klo sedih biasanya ngapain",
"Spil orang paling gajelas",
"Pernah nyakitin cp kamu? Ceritain",
"Skrng sayang sama siapa?",
"Spil guru tergalak pas sd",
"Spil tugas yang pernah ga dikerjain",
"Gimana rasanya jadi pelampiasan",
"Spil yang kamu doakan di sepertiga malammu",
"Spil yang suka halu",
"Spil guru/dosen yang paling ngeselin",
"Spil first bias lu waktu baru masuk kedunia kpop",
"Spil orang yang terakhir lu gombalin",
"Spil guru tergalak pas sd",
"Spil cowo idaman Lo?",
"Lagi deket sama siapa sekarang!",
"Spil yang suka halu",
"Spil sifat orang yang bikin lu ilfeel",
"Spil orang yg paling ngangenin",
"Spil yang sering jadi korban fakboy",
"Spil kencan idaman",
"Spil chat pas nembak doi",
"Spil yg pernah jadi ttm lu",
"Spil kepikiran mau nikah umur berapa?",
"Spill makanan yg lu suka",
"Spil temen sekelas yang pernah disukain",
"Spil yang bikin kamu semangat!",
"Spil mantan yang paling brengsek",
"Pernah belok ga?",
"Spil warna rambut yang pengen dicoba",
"Spil terakhir gosipin guru/dosen",
"Spil gebetan lo sekarang",
"Spil orang terganteng di gc ini",
"Pernah baku hantam sma org ketiga?",
"Spil ngapain aja lu kalo telponan",
"Spil siapa yang paling bawel (tag)",
"Spil jadian terlama berapa bulan/tahun?",
"Spil your fav emoji",
"Spil abang ter debest",
"Spill siapa orang yang selalu ada buat lo",
"Spill screenshot isi galeri (gambar muka bisa disensor)",
"Spill yang suka ngambekan di gc",
"Spill nomor emak rl",
"Spill orang yg nemenin lu 24/7",
"Spill cowo/cewe yang menurut lo paling cakep di gc ini",
"Spill siapa yg suka overthinking",
"Spill kapan terakhir kali pacaran",
"Hal yang paling cringe",
"Spill kapan terakhir kali ngompol",
"Spill recent call wa",
"Spill kakel yg pernah ngelabrak lu",
"Spill nama orang tua lo",
"Spill pernah ketauan selingkuh?",
"siapa orang yang paling perhatian?",
"Spill adik kelas yang nyebelin",
"Spill orang yg bikin lu mood lagi",
"Spill menunggu atau menanti?",
"Spill, terakhir tidur jam berapa",
"Spill kalian kalo mandi apa yang pertama kalian lakukan",
"Spill yang sering berantem/ribut sama cp",
"Spill cowo pertama yang lu tangisin",
"Spill siapa yg bikin lu jatuh cinta pas liat tingkanya",
"Spill pujian yang paling berkesan manurut kamu",
"Spill screenshots pencarian youtube",
"lagu apa yang buat lo sedih?",
"Spill foto calon masdep",
"Spill se - brengsek apa diri lu",
"Spill Sahabat terbaikmu",
"Spill warna kesukaan lu",
"Spill yang paling ngeselin",
"siapa yg paling nyebelin?",
"Siapa yg pernah neror/ ngelabrak lu? Tag!",
"kalo punya kakak cowok mau dikenalin ke siapa di antara temen-temen?",
"Spill anak keberapa dari berapa saudara",
"Spill kado ulang tahun paling the best",
"siapa anak dakjal di grup ini?",
"Spill wallpaper hp",
"Spill yang orang yang sering phpin kamu",
"Spill uname ig lu",
"Spill foto muka lo pas lagi nangis",
"Spill nama boneka kalian",
"Spill mimpi kalian yang teraneh",
"Spill hal terdrama dihidup km",
"Spill siapa yg paling males disini",
"Spill lebih suka yg panjang tp kecil atau pendek tp gede",
"Spill lu lagi ngapain",
"Spill orang yg pernah jatuh cinta tpi sama dua orang yg berbeda tag!",
"Spill tugas yang pernah ga dikerjain",
"Spill jodoh",
"Spill yang sering traktir lu",
"Spill chat sama temen",
"Spill nama mantan yang ngeselin",
"Spill recent call wa",
"Kamu kepikiran buat nikah gak sama cp mu?",
"Spill ss history youtube",
"Spill org yg paling lucu",
)